apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurementmanagement
  namespace: procurement
  labels:
    app: procurementmanagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: procurementmanagement
  template:
    metadata:
      labels:
        app: procurementmanagement
    spec:
      containers:
        - name: procurementmanagement
          image: user06acr.azurecr.io/procurementmanagement:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 250m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5