---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurementmanagement
  labels:
    app: procurementmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurementmanagement
  template:
    metadata:
      labels:
        app: procurementmanagement
    spec:
      containers:
        - name: procurementmanagement
          image: username/procurementmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurementrequest
  labels:
    app: procurementrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurementrequest
  template:
    metadata:
      labels:
        app: procurementrequest
    spec:
      containers:
        - name: procurementrequest
          image: username/procurementrequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodsdelivery
  labels:
    app: goodsdelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodsdelivery
  template:
    metadata:
      labels:
        app: goodsdelivery
    spec:
      containers:
        - name: goodsdelivery
          image: username/goodsdelivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      containers:
        - name: mypage
          image: username/mypage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: username/notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: procurementmanagement
  labels:
    app: procurementmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: procurementmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: procurementrequest
  labels:
    app: procurementrequest
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: procurementrequest


---


apiVersion: v1
kind: Service
metadata:
  name: goodsdelivery
  labels:
    app: goodsdelivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: goodsdelivery


---


apiVersion: v1
kind: Service
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mypage


---


apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notification

