apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurementrequest
  labels:
    app: procurementrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurementrequest
  template:
    metadata:
      labels:
        app: procurementrequest
    spec:
      containers:
        - name: procurementrequest
          image: username/procurementrequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5