apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurementrequest
  namespace: procurement
  labels:
    app: procurementrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurementrequest
  template:
    metadata:
      labels:
        app: procurementrequest
    spec:
      containers:
        - name: procurementrequest
          image: user06acr.azurecr.io/procurementrequest:v7
          ports:
            - containerPort: 8080
          env:
            - name: procurement-url
              valueFrom:
                configMapKeyRef:
                  name: procurement-cm
                  key: url
          #readinessProbe:
          #  httpGet:
          #    path: '/actuator/health'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
          #livenessProbe:
          #  httpGet:
          #    path: '/actuator/failed'
          #    port: 8090
          #  initialDelaySeconds: 120
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 5
          volumeMounts:
            - name: volume
              mountPath: "/mnt/azure"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: procurementrequest-disk