apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurementrequest
  namespace: procurement
  labels:
    app: procurementrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurementrequest
  template:
    metadata:
      labels:
        app: procurementrequest
    spec:
      containers:
        - name: procurementrequest
          image: procurementacr.azurecr.io/procurementrequest:v2
          ports:
            - containerPort: 8080
          env:
            - name: procurement-url
              valueFrom:
                configMapKeyRef:
                  name: procurement-cm
                  key: url
      imagePullSecrets:
        - name: regcred
          #readinessProbe:
          #  httpGet:
          #    path: '/deliveryrequests'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
          #livenessProbe:
          #  httpGet:
          #    path: '/deliveryrequests/failed'
          #    port: 8080
          #  initialDelaySeconds: 120
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 5