apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v-disk
  namespace: procurement
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi