apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodsdelivery
  namespace: procurement
  labels:
    app: goodsdelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodsdelivery
  template:
    metadata:
      labels:
        app: goodsdelivery
    spec:
      containers:
        - name: goodsdelivery
          image: procurementacr.azurecr.io/goodsdelivery:v1
          ports:
            - containerPort: 8080
          #readinessProbe:
          #  httpGet:
          #    path: '/goodsdeliveries'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
          #livenessProbe:
          #  httpGet:
          #    path: '/goodsdeliveries'
          #    port: 8080
          #  initialDelaySeconds: 120
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 5