apiVersion: v1
kind: Service
metadata:
  name: goodsdelivery
  namespace: procurement
  labels:
    app: goodsdelivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: goodsdelivery